apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-deployment
  labels:
    app: laravel-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      containers:
        # Laravel Application Container
        - name: app
          image: kongchankiry/laravel-app:latest
          ports:
            - containerPort: 9000
          env:
            - name: DB_HOST
              value: "mysql-service"  # Ensure MySQL service name matches the database Service [[1]]
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: "kongchankiry-db"
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWORD
              value: "Hello@123"
          volumeMounts:
            - name: laravel-code
              mountPath: /var/www/html
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"

        # Nginx Web Server
        - name: web
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: laravel-code
              mountPath: /var/www/html
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 5
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"

      volumes:
        - name: laravel-code
          emptyDir: {}  # Replace with PersistentVolumeClaim for production [[9]]
        - name: nginx-config
          configMap:
            name: nginx-config