apiVersion: v1
kind: Service
metadata:
  name: laravel-service
spec:
  type: NodePort
  selector:
    app: laravel-app
  ports:
    - name: http
      port: 8087
      targetPort: 80
      nodePort: 30087  # Ensure this port is available on the node [[2]]